### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [MultiSafepay/php-sdk#1]
When installing this package with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `MultiSafepay\Api\Transactions\OrderRequest\GatewayInfo\QrEnabled` located in `./vendor/multisafepay/php-sdk/src/Api/Transactions/OrderRequest/Arguments/GatewayInfo/QrEnabled.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/Api/Transactions/OrderRequest/Arguments/GatewayInfo/QrEnabled.php src/Api/Transactions/OrderRequest/GatewayInfo/QrEnabled.php
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by Jasper-MultiSafepay** [comment]
@brandonkelly 
Thanks for reporting this, I just pushed a patch version of our SDK (4.0.1) which solves the issue.
I'll let the team recheck the Craft Commerce plugin and create a new release.

**Comment by brandonkelly** [comment]
Thanks :)

**Comment by Joris-MultiSafepay** [comment]
@brandonkelly 
We just did [a new release](https://github.com/MultiSafepay/craft-commerce/releases/tag/1.1.0) for the plugin which, once installed, will also automatically update our SDK to the latest version and thus solve this issue. 
Thanks for reporting this.
