### ISSUE TITLE
MultiSafepay PHP SDK throws 412 Unknown Data when API is out

### ISSUE THREAD

**Issue by LeonidasJP** [MultiSafepay/php-sdk#10]
The MultiSafepay PHP SDK throws an "412 Unknown Data" ApiException, telling it can't parse the 503 Service Unavailable page. Is it possible to change this to - for example - an ApiUnavailableException (extending ApiException for backward compatibility), so we can handle outages of the MultiSafepay API easier than parsing the response body to see what's up?

**Comment by danielcivit** [comment]
Hi @LeonidasJP.

Thanks for contacting us and for your feedback.

I just created a backlog item for this purpose.  

I will get back to you via this ticket as soon as we release a new version, including these changes.

**Comment by LeonidasJP** [comment]
Hi @danielcivit,
Thanks for the fast response! And my compliments to the crew out there for quickly mitigating this morning's downtime :-D

**Comment by danielcivit** [comment]
Hello @LeonidasJP 

We just released the 5.14.0 version, and now the SDK  will throw the ApiUnavailableException if the API returns 503 HTTP code.   

Once again, thank you for your interest and valuable comment in using our PHP-SDK.

Feel free to reopen this ticket, or create a new one, if you have any other comments for us.
