### ISSUE TITLE
Missing properties in UpdateRequest

### ISSUE THREAD

**Issue by malles** [MultiSafepay/php-sdk#14]
As per the [documentation for 'Update or cancel order'](https://docs.multisafepay.com/reference/updateorder) an order can be updated with extra info concerning shipping, invoicing and more. This endpoint is also used to update the status for cancelling.

At the moment the class [`MultiSafepay\Api\Transactions\UpdateRequest`](https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Transactions/UpdateRequest.php) only supports the `id`  and `status` properties for cancelling an order.

In my implementation I need to update the order to be able to attach an `invoice_id` for accounting purposes. I have now managed to do that by extending the UpdateRequest class with that property.

Could it be possible to extend the original code with the possible fields listed in the documentation to offer a more complete interface?

**Comment by danielcivit** [comment]
Hi @malles 

Thanks for your interest and comments. It is certainly a point that can be improved and we will create a backlog item for this purpose.

However, let me explain you can do this within the SDK:

The UpdateRequest object extends from RequestBody object.
https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Transactions/UpdateRequest.php#L16

The RequestBody object extends from DataObject object.
https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Base/RequestBody.php#L15C7-L15C18

In the DataObject there is a method called addData();
https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Base/DataObject.php#L13

Using this method, you should be able to add the invoice ID to the updateRequest object:

It will be something like:

```
use MultiSafepay\Api\Transactions\OrderRequest;

$orderRequest = new OrderRequest();
$orderRequest->addData( 
  array( 'invoice_id' => 'INVOICE-ID' )
);
```

We will come back to you, once a new release is done, improving the UpdateRequest object.

**Comment by malles** [comment]
Thanks for your quick response and the workaround. I had not spotted the generic `addData` possibility, that might come in handy for other cases. I'll stick with the extension I have now.

This issue can be closed for now, having a good workaround and knowing it is on the radar is fine.

**Comment by danielcivit** [comment]
Hi @malles 

Just passing by to share that we just released a new version of the SDK. 

This one contains new properties in the [MultiSafepay\Api\Transactions\UpdateRequest](https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Transactions/UpdateRequest.php)

Now, it is possible to define new properties, including "invoice_id", via the abstraction provided by this object. 

Once again, thanks for your comments and feedback.
